
package prolab2;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author doguk
 */
public class FormListe extends javax.swing.JFrame {

    String arac;
    
    public FormListe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        KaraGoster = new javax.swing.JButton();
        HavaGoster = new javax.swing.JButton();
        DenızGoster = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        yazi_alani = new javax.swing.JTextArea();
        geri_don = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listeleme Sonucu");

        KaraGoster.setText("Kara Taşıtları");
        KaraGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaraGosterActionPerformed(evt);
            }
        });

        HavaGoster.setText("Hava Taşıtları");
        HavaGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HavaGosterActionPerformed(evt);
            }
        });

        DenızGoster.setText("Deniz Taşıtları");
        DenızGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenızGosterActionPerformed(evt);
            }
        });

        yazi_alani.setColumns(20);
        yazi_alani.setRows(5);
        yazi_alani.setKeymap(null);
        jScrollPane1.setViewportView(yazi_alani);

        geri_don.setText("Bir Önceki Menüye Dön");
        geri_don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_donActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HavaGoster)
                            .addComponent(KaraGoster)
                            .addComponent(DenızGoster))
                        .addGap(160, 160, 160)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(geri_don, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KaraGoster)
                        .addGap(33, 33, 33)
                        .addComponent(DenızGoster)
                        .addGap(37, 37, 37)
                        .addComponent(HavaGoster))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(geri_don)
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KaraGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaraGosterActionPerformed
       try(FileReader fileReader = new FileReader("arackayitlari.txt")){
       String line;
       BufferedReader br = new BufferedReader(fileReader);
       
           try {
               while ((line = br.readLine())!=null) {
                   String[] dizi=line.split(":");
                   
                   if((dizi[0].equals("Otomobil Id"))||( dizi[0].equals("Bisiklet Id"))){
                       
                       
                       yazi_alani.append(line+"\n");
                       
                   }


               } } catch (IOException ex) {
               Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
           }
} catch (FileNotFoundException ex) {
            Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_KaraGosterActionPerformed

    private void DenızGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenızGosterActionPerformed
               try(FileReader fileReader = new FileReader("arackayitlari.txt")){
       String line;
       BufferedReader br = new BufferedReader(fileReader);
       
           try {
               while ((line = br.readLine())!=null) {
                   String[] dizi=line.split(":");
                   
                   if(dizi[0].equals("Gemi Id")){
                       
                       
                       yazi_alani.append(line+"\n");
                       
                   }


               } } catch (IOException ex) {
               Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
           }
} catch (FileNotFoundException ex) {
            Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DenızGosterActionPerformed

    private void HavaGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HavaGosterActionPerformed
                      
        
        try(FileReader fileReader = new FileReader("arackayitlari.txt")){
       String line;
       BufferedReader br = new BufferedReader(fileReader);
       
           try {
               while ((line = br.readLine())!=null) {
                   String[] dizi=line.split(":");
                   
                   if(dizi[0].equals("Ucak Id")){
                       
                       
                       yazi_alani.append(line+"\n");
                       
                   }


               } } catch (IOException ex) {
               Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
           }
} catch (FileNotFoundException ex) {
            Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormListe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HavaGosterActionPerformed

    private void geri_donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_donActionPerformed
        NewJFrame jw= new NewJFrame();
        jw.setVisible(true);
        dispose();
    }//GEN-LAST:event_geri_donActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DenızGoster;
    private javax.swing.JButton HavaGoster;
    private javax.swing.JButton KaraGoster;
    private javax.swing.JButton geri_don;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea yazi_alani;
    // End of variables declaration//GEN-END:variables
}
